export const BASE_URL = "https://proposals.world/api";

export const ENDPOINTS = {
  LOGIN: "/login",
  REGISTER: "/register",
  VERIFY_OTP: "/verify-otp",
  FETCH_PROFILE: "/me",
  FETCH_DETAILED_PROFILE: "/profile",
  LOGOUT: "/logout",
  UPDATE_PROFILE_IMAGE: "/user/profile/photo",
  RESEND_OTP_MASSAGE: "/resend-verification-link",
  PASSWORD_RESET_REQUEST: "/password/email",
  PASSWORD_RESET: "/password/reset",
  PASSWORD_VERIFY_OTP: "/password/verify-otp",
  PERSONAL_ATTRIBUTES: "/personal-attributes",
  LIFESTYLE_INTERESTS: "/lifestyle-interests",
  PROFESSIONAL_EDUCATIONAL: "/professional-educational",
  GEOGRAPHIC: "/geographic",
  CITIES: "/countries",
  SOCIAL_MEDIA_PRESENCES: "/social-media-presences",
  JOB_TITLES: "/job-titles",
  USER_PREFERENCES: "/user-preferences",
  GET_USER_PREFERENCES: "/show-user-preferences",
  GET_USER_PREFERENCES_AND_SUGGESTIONS: "/users/filter",
  USER_PROFILE: "/user-profile",
  LIKE_USER: "/like",
  DISLIKE_USER: "/dislike",
  MATCHES: "/matches",
  GET_LIKES: "/getlikes",
  REPORT_USER: "/report-user",
  SUBSCRIPTION_CARDS: "/subscription-cards",
  GET_LIKED_BY_ME: "/liked-by",
  TICKETS: "/tickets",
  MATCHES: "/matches",
  REVEAL_CONTACT: "/reveal-contact",
};
