import { StyleSheet, Dimensions } from "react-native";
import COLORS from "../constants/colors";
const { width } = Dimensions.get("window");

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.primary,
  },
  gradient: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  header: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 15,
  },
  headerTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerIcon: {
    marginRight: 8,
  },
  headerText: {
    color: COLORS.white,
    fontSize: 22,
    fontWeight: "bold",
  },
  closeButton: {
    padding: 8,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 20,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 30,
  },
  content: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  matchBadge: {
    backgroundColor: COLORS.white,
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  matchPercentage: {
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: "bold",
    marginRight: 4,
  },
  matchLabel: {
    color: COLORS.text,
    fontSize: 14,
  },
  profileContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    marginBottom: 20,
  },
  profileCard: {
    width: width * 0.38,
    height: width * 0.5,
    borderRadius: 20,
    overflow: "hidden",
    backgroundColor: COLORS.white,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  profileImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  profileInfo: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 12,
  },
  profileName: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 2,
  },
  profileLocation: {
    flexDirection: "row",
    alignItems: "center",
  },
  locationText: {
    color: COLORS.white,
    fontSize: 12,
    marginLeft: 4,
  },
  profileConnector: {
    alignItems: "center",
    width: width * 0.08,
  },
  connectorLine: {
    height: 1,
    width: width * 0.08,
    backgroundColor: COLORS.white,
  },
  connectorCircle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
    margin: 6,
  },
  detailsContainer: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    width: "100%",
    paddingVertical: 50,
    paddingHorizontal: 20,
    minHeight: 600,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.text,
    marginBottom: 20,
    textAlign: "center",
  },
  detailsContent: {
    paddingBottom: 20,
  },
  detailCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    backgroundColor: COLORS.background,
    borderRadius: 12,
    marginBottom: 12,
  },
  detailContent: {
    marginLeft: 12,
    flex: 1,
  },
  detailTitle: {
    fontSize: 14,
    color: COLORS.text,
    opacity: 0.7,
    marginBottom: 2,
  },
  detailValue: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.text,
  },
  matchTextContainer: {
    marginTop: 15,
    marginBottom: 25,
    paddingHorizontal: 6,
  },
  matchText: {
    fontSize: 15,
    color: COLORS.text,
    opacity: 0.8,
    lineHeight: 22,
    textAlign: "center",
  },
  viewProfileButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 10,
    marginHorizontal: 20,
  },
  viewProfileText: {
    color: COLORS.white,
    fontWeight: "600",
    fontSize: 16,
  },
  loadingText: {
    color: COLORS.white,
    fontSize: 16,
    marginTop: 10,
  },
  errorContainer: {
    padding: 20,
    alignItems: "center",
  },
  errorText: {
    color: COLORS.white,
    fontSize: 16,
    marginBottom: 20,
    textAlign: "center",
  },
  retryButton: {
    backgroundColor: COLORS.white,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
  },
  retryText: {
    color: COLORS.primary,
    fontWeight: "600",
    fontSize: 16,
  },
});
